services:
  backend:
    build:  ./server
    container_name: backend-container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    

  frontend:
    build: ./client
    container_name: frontend-container
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend
      
